Dev 68214 remove linkedin news
CanadianClimateDataPortal/climatedata-wp-theme pull request #275
Opened 2024-08-21 21:06 UTC by mledezma

## Description

Removing script on function.php that was displaying a unnecessary LinkedIn Share button.

## Related ticket

- https://rm.ewdev.ca/issues/68214

> Make sure to read the *Pull requests process* in CONTRIBUTING.md.
> 
> Main points:
> 
> * The assigned reviewer(s) must always *submit* a review (not simply add a
>   comment).
>
> * If the PR is "Approved", the creator of the PR must then:
>   * Implement the changes in the reviewer's comments, if applicable, and mark
>     them as "Resolved".
>   * Squash and merge the branch.
>   * Delete the branch.
> 
> * If the PR is "Request Changes", the creator of the PR must then:
>   * Update the code as requested.
>   * Re-request a review from the reviewer.
>   * NOT mark the comments as "Resolved", the reviewer will.
> 
> (You can keep or remove this block, as you wish.)

2024-08-22 17:53 UTC, domcode-ew requested changes

2024-08-22 17:53 UTC, domcode-ew commented on fw-child/functions.php
> +<script src="https://platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script>]
```suggestion
<script src="https://platform.linkedin.com/in.js" type="text/javascript">lang: en_US</script>
```

2024-08-28 17:18 UTC, domcode-ew approved these changes

2024-08-30 13:35 UTC, xfrenette-crim requested changes

2024-08-30 13:35 UTC, xfrenette-crim commented on fw-child/functions.php
> -<script type="IN/Share" data-url="https://www.linkedin.com"></script>
The button is removed, but then the included scripts above are included needlessly. It's probably the whole `if` that needs to be removed.

2024-09-04 14:05 UTC, domcode-ew approved these changes

2024-09-06 15:32 UTC, xfrenette-crim approved these changes
Approved with small change.

2024-09-06 15:32 UTC, xfrenette-crim commented on fw-child/functions.php
I would remove the `// FB/linkedin share scripts` comment on line 424 since it's not correct anymore, and it doesn't add useful information (the code is simple to understand).

2024-09-09 13:04 UTC, merged