Clim 359 shareable url
CanadianClimateDataPortal/climatedata-wp-theme pull request #42
Opened 2023-05-09 19:00 UTC by ahandan

Ajout d'un url de partage.

Les inputs du form sont verser dans l'url,
L'url du browser est mis à jours
Le button copier lien exist sous la list des choix de paramètre et permet de copier le lien de partage.

2023-05-23 15:15 UTC, perronld requested changes

2023-05-23 16:19 UTC, perronld commented on climate-data-ca/resources/js/analyze-functions.js
> +            fetch("https://dataclimatedata.crim.ca/get-gids/"+compressedValue+"?gridname=canadagrid")
variable globale disponible: data_url

2023-06-06 14:03 UTC, perronld requested changes
N.B.  il manque toujours beaucoup de point-virgules.

2023-06-06 14:16 UTC, perronld commented on climate-data-ca/resources/js/analyze-functions.js
> +            paramsDict["form_thresholds"] = JSON.parse(decodeURI(paramsDict["form_thresholds"]))
I'm getting an exception here when switching language. Google Analytics appends something to the query string. ex.:https://dev-fr.climatedata.ca/analyser/?_gl=1*19kjqll*_ga*MTIyOTg2MTI4Ny4xNTYyNTg3MjE4*_ga_CPGH39EQSH*MTY4NjA1OTk4Mi4yMTcuMS4xNjg2MDYwMDA5LjAuMC4w

2023-06-12 20:55 UTC, perronld commented on climate-data-ca/resources/js/analyze-functions.js
> +            let baseUrl = document.URL.split('?')[0];
They need to be lost in my opinion. Especially any Google Analytics tracking.. since it's doesn't apply to another user.

2023-06-19 19:27 UTC, ahandan commented
> @ahandan Des nouvelles concernant les commentaires à adresser?

Je pense que le tout est bon, la branche est en démo pour des tests. Idéalement si vous êtes en mesure de le briser avec des tests ça nous donnera un état des lieux, sinon ça reste toujours une démo pour le temps du WireFrame2.0

2023-10-12 22:54 UTC, closed without merging